spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SmartStorageDev
    username: root
    password: ToadFace01
    
  jpa:
    hibernate:
      ddl-auto: validate

debug: true

