spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:file:///Users/klm96551/.smartstorage/smartstorage115.sqlite
    
  jpa:
    hibernate:
      ddl-auto: validate

debug: false

